### ISSUE TITLE
困扰很久使用idea编写html如何像vscode一样提示代码

### ISSUE THREAD

**Issue by songmeng** [songmeng/Sunburst#42]
<h4>问题描述：</h4>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;之前一直在自学前端的东西，在一阵尝试新奇事物的驱动下下载并尝试了vscode，之后以后在用vscode练习学习html、css和js，说实话vscode真的是良心之作，简洁、实用。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;显然相较于vscode来说idea显得“厚重”，当然两者定位本就不同，一个是ide一个是文本编辑器。 有时候学习+练习时不仅仅会需要写前端的东西，最简单的有时候会用到java，
    有时候还需要运行整个项目。这时候还是idea，可是之前用vscode用习惯了，十分喜欢vscode写html时的代码提示方式，一般是 标签 + Enter ，整个标签就展示出来了。用idea编写html时提示什么的都没什么问题，只是idea默认代码触发
是Tab键，尝试改为Enter键，之前试了很多方法都没成功</p>
<p>网上搜的大部分思路都是通过设置live templates</p>
<p>尝试了很多方法</p>
<ul>
    <li>设置代码提示触发键Settings > Editor > Space/Tab/Enter/Custom...</li>
    <li>livetemplates中HTML/XML修改Expand with Space/Tab/Enter/Default Enter</li>
    <li>livetemplates中Zen HTML调整</li>
</ul>
<img src="https://i.postimg.cc/g2db6L1t/idea-live-templates20191011.png" alt="live-templates" width="400px">
<p>以上方法设置都没有效果，今天无意中看到了Editor > Emmet 选项中Expand abbreviation with Space/Tab/Enter/Custom...</p>
<p>选项改为了Enter成功了，可以愉快的在Idea和vscode敲代码了</p>
<img src="https://i.postimg.cc/yY0zdypS/idea-emmet20191011.png" alt="emmet" width="400px">

**Comment by Hastings37** [comment]
感谢感谢
